alitajs/DynamicForm

.fatherrc.ts, config/config.ts, mock/app.ts, package.json, src/DynamicForm.tsx, src/components/NomarDatePicker/index.tsx, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.tsx, src/components/NomarSwitch/index.tsx, src/components/NomarTextArea/index.tsx, src/components/OnlyReadInput/index.tsx, src/components/index.tsx, src/demo/index.tsx, src/index.md, src/index.tsx, src/styles/index.less
feat: add NomarPicker NomarSwitch NomarTeatArea OnlyReadInput DynamicForm
=> feat: add more components

config/config.ts, config/plugin.ts, package.json, src/DynamicForm.tsx, src/EditForm.tsx, src/NewFieldPicker.tsx, src/components/ExtraInput/index.tsx, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.tsx, src/components/NomarRadio/index.tsx, src/components/OnlyReadInput/index.tsx, src/components/RangeDatePicker/index.tsx, src/pages/index.tsx
合并另一个项目的代码，另一个项目封版本了。
组件开发：
```
yarn dev
```
文档开发
```
yarn start
```
文档编译
```
build:doc
```
组件编译
```
yarn build
```
=> feat: merge xiaohuoni dform

config/config.ts, package.json
=> feat: add env

src/components/NomarPicker/demo/normalSelect.tsx, src/components/NomarPicker/demo/onlyRead.tsx, src/components/NomarPicker/demo/requiredSelect.tsx, src/components/NomarPicker/index.md, src/components/NomarRadio/demo/normalRadio.tsx, src/components/NomarRadio/demo/onlyRead.tsx, src/components/NomarRadio/index.md
=> B select and radio

src/components/ExtraInput/demo/positionInput.tsx, src/components/ExtraInput/demo/priceInput.tsx, src/components/ExtraInput/demo/selectExtra.tsx, src/components/ExtraInput/index.md
=> Feat extra input

src/components/RangeDatePicker/index.tsx, src/styles/index.less
1、fix radio component excessive effect of style
2、fix rangeDatePicker and ExtraInput error style
=> fix: radio style and rangeDatePicker style

src/components/NomarDatePicker/index.tsx, src/components/RangeDatePicker/index.tsx
=> fix: picker and datepicker no title

src/DynamicForm.tsx, src/components/ExtraInput/demo/index.tsx, src/components/ExtraInput/demo/priceInput.tsx, src/components/ExtraInput/index.md, src/components/NomarInput/demo/index.tsx, src/components/NomarInput/demo/titleTooLong.tsx, src/components/NomarInput/index.md, src/components/NomarTextArea/demo/index.tsx, src/components/NomarTextArea/demo/titleTooLong.tsx, src/components/NomarTextArea/index.md
=> fix: NomarInput and ExtraInput title too long will be blocked

src/components/RangeDatePicker/demo/index.tsx, src/components/RangeDatePicker/index.tsx
The endDate cannot be less than the beginDate. the beginDate cannot be large than the endDate.
if set initialValue ,the beginDate and endDate will set it auto;
=> fix: rangeDatePicker set date linkage

src/DynamicForm.tsx, src/components/NomarCheckBox/demo/checkbox.tsx, src/components/NomarCheckBox/demo/index.tsx, src/components/NomarCheckBox/index.md, src/components/NomarCheckBox/index.tsx, src/components/NomarDatePicker/index.md, src/components/index.tsx, src/styles/index.less
=> feat: NomarCheckbox

src/components/index.tsx
need export IFormItemProps, IDynamicFormProps from DynamicForm.tsx
need insert  data to  bind IFormItemProps
=> fix: export IFormItemProps and IDynamicFormProps

src/DynamicForm.tsx
export onValueChange and delete console it
=> fix: export onValueChange

src/components/NomarDatePicker/demo/index.tsx, src/components/NomarDatePicker/index.md, src/components/RangeDatePicker/index.md, src/index.tsx, src/utils/index.tsx
in Safari ,change the date value to new Date(2020, 02, 02, 22, 22).
write a public function to change the value. the function name is 'dateChange', user can use it form '@alitajs/dform'
=> fix: date Value change

config/config.ts, src/components/ExtraInput/index.md, src/components/ExtraInput/index.tsx, src/components/NomarCheckBox/index.md, src/components/NomarCheckBox/index.tsx, src/components/NomarDatePicker/index.md, src/components/NomarDatePicker/index.tsx, src/components/NomarInput/index.md, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.md, src/components/NomarPicker/index.tsx, src/components/NomarRadio/index.md, src/components/NomarRadio/index.tsx, src/components/NomarSwitch/index.md, src/components/NomarSwitch/index.tsx, src/components/NomarTextArea/index.md, src/components/NomarTextArea/index.tsx, src/components/RangeDatePicker/index.md, src/components/RangeDatePicker/index.tsx, src/styles/index.module.less
user can set title fonSize in `config/config.ts`
=> Feat font size

src/DynamicForm.tsx, src/components/ExtraInput/index.md, src/components/ExtraInput/index.tsx, src/components/NomarCheckBox/index.md, src/components/NomarCheckBox/index.tsx, src/components/NomarDatePicker/index.md, src/components/NomarDatePicker/index.tsx, src/components/NomarInput/index.md, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.md, src/components/NomarPicker/index.tsx, src/components/NomarRadio/index.md, src/components/NomarRadio/index.tsx, src/components/NomarSwitch/index.md, src/components/NomarSwitch/index.tsx, src/components/NomarTextArea/index.md, src/components/NomarTextArea/index.tsx, src/components/RangeDatePicker/index.md, src/components/RangeDatePicker/index.tsx
if the field is required, the red Star will appear, if user want to hide the star,set hasStar false；
=> Feat has star

src/styles/index.module.less
=> fix: line margin auto

package.json, src/components/NomarRadio/index.tsx, src/styles/index.module.less
=> Fix radio and area

src/styles/index.less
=> fix: NomarTextArea

src/components/NomarTextArea/demo/extraArea.tsx, src/components/NomarTextArea/demo/index.tsx, src/components/NomarTextArea/index.md, src/components/NomarTextArea/index.tsx, src/styles/index.less
Auto set positionType is vercital if extra exists in the field
=> feat: NomarTextArea insert extra

config/config.ts, package.json, src/components/ExtraInput/index.tsx, src/components/Field/index.tsx, src/components/NomarCheckBox/index.tsx, src/components/NomarDatePicker/index.tsx, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.tsx, src/components/NomarRadio/index.tsx, src/components/NomarSwitch/index.tsx, src/components/NomarTextArea/index.tsx, src/components/RangeDatePicker/index.tsx, src/pages/index.tsx, src/styles/index.less
Set the text color and placeholder color  be different
=> feat: set select value color

src/components/Field/index.tsx, src/index.tsx, src/styles/index.less
export Field, Form and useForm form rc-field-form, user can use them form @alitajs/dform
=> Feat：export Field field

src/components/ExtraInput/index.md, src/components/NomarCheckBox/index.md, src/components/NomarDatePicker/index.md, src/components/NomarInput/index.md, src/components/NomarPicker/index.md, src/components/NomarRadio/index.md, src/components/NomarSwitch/index.md, src/components/NomarTextArea/index.md, src/components/RangeDatePicker/index.md, src/setting.md
insert setting doc .Users can know some custom properties and notes from it
=> doc: insert settingMd

src/components/Field/index.tsx, src/components/RangeDatePicker/demo/index.tsx, src/components/RangeDatePicker/index.tsx, src/pages/index.tsx, src/styles/index.less, typings.d.ts
1、重构了时间选择区间的代码
2、修复了设置placeholder无效的bug
=> feat: recode range date picker

package.json, src/DynamicForm.tsx, src/components/RangeDatePicker/demo/index.tsx, src/components/RangeDatePicker/index.md, src/components/RangeDatePicker/index.tsx
insert firstProps and secondProps field
=> feat: rangerDatePicker 

src/DynamicForm.tsx, src/components/ExtraInput/index.tsx, src/components/NomarCheckBox/index.tsx, src/components/NomarDatePicker/index.tsx, src/components/NomarInput/demo/index.tsx, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.tsx, src/components/NomarRadio/index.tsx, src/components/NomarSwitch/index.tsx, src/components/NomarTextArea/index.tsx, src/index.tsx, src/setting.md
用户使用 rules进行规则校验编写会有类型错误的报错提示。从 rc-field-form 导出 Rule 规则，进行规则类型校验，
=> feat: Rule

package.json, src/DynamicForm.tsx, src/components/NomarRadio/demo/index.tsx, src/components/NomarRadio/demo/verticalRadioType.tsx, src/components/NomarRadio/index.md, src/components/NomarRadio/index.tsx, src/styles/index.less
Nomarradio insert field radioType, user can set it 'horizontal' or 'vercital', if radioType is 'vercital', positionType will change it to 'vercital'
=> feat: insert radioType

.fatherrc.ts, package.json, src/DynamicForm.tsx, src/components/CoverRadio/demo/basicRadio.tsx, src/components/CoverRadio/demo/index.tsx, src/components/CoverRadio/demo/itemVertical.tsx, src/components/CoverRadio/demo/vertical.tsx, src/components/CoverRadio/index.md, src/components/CoverRadio/index.tsx, src/components/CoverRadio/radioGroup.tsx, src/components/index.tsx, src/styles/index.less
=> feat: CoverRadio

src/DynamicForm.tsx, src/components/NomarImagePicker/demo/index.tsx, src/components/NomarImagePicker/demo/insertImg.tsx, src/components/NomarImagePicker/demo/noInsertImg.tsx, src/components/NomarImagePicker/demo/showImg.tsx, src/components/NomarImagePicker/index.md, src/components/NomarImagePicker/index.tsx, src/components/index.tsx, src/setting.md
=> feat: NomarImagePicker

package.json, src/components/NomarImagePicker/index.tsx, src/styles/index.less
fix border bottom and publish version 1.0.5
=> fix: NomarImagePicker

src/DynamicForm.tsx, src/components/NomarCustom/demo/index.tsx, src/components/NomarCustom/index.md, src/components/NomarCustom/index.tsx, src/components/index.tsx, src/styles/index.less
=> feat: NomarCustom

src/DynamicForm.tsx, src/components/NomarInput/demo/index.tsx, src/components/NomarInput/index.tsx, src/styles/index.less
if positionType set vertical , extra is display
=> fix: NomarInput extra

package.json, src/components/CoverRadio/index.md, src/components/CoverRadio/index.tsx, src/components/ExtraInput/index.md, src/components/ExtraInput/index.tsx, src/components/NomarCheckBox/index.md, src/components/NomarCheckBox/index.tsx, src/components/NomarCustom/index.md, src/components/NomarCustom/index.tsx, src/components/NomarDatePicker/index.md, src/components/NomarDatePicker/index.tsx, src/components/NomarImagePicker/index.md, src/components/NomarImagePicker/index.tsx, src/components/NomarInput/demo/index.tsx, src/components/NomarInput/index.md, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.md, src/components/NomarPicker/index.tsx, src/components/NomarRadio/index.md, src/components/NomarRadio/index.tsx, src/components/NomarTextArea/index.md, src/components/NomarTextArea/index.tsx, src/components/RangeDatePicker/index.md, src/components/RangeDatePicker/index.tsx, src/styles/index.less
Add a subtitle to the right of the title
=> feat: insert subTitle

package.json, src/components/Field/index.tsx, src/components/NomarCheckBox/index.tsx, src/components/NomarRadio/index.tsx, src/styles/index.less
user can set value and placeHolder font size with @alita-dform-select-font-size
=> feat: value font size

package.json, src/DynamicForm.tsx, src/components/CoverRadio/index.md, src/components/MultiplePicker/demo/index.tsx, src/components/MultiplePicker/index.md, src/components/MultiplePicker/index.tsx, src/components/MultiplePicker/multiplePickerGroup.tsx, src/components/NomarCheckBox/index.md, src/components/NomarRadio/index.md, src/components/RangeDatePicker/index.tsx, src/components/index.tsx, src/demo/index.tsx, src/setting.md, src/styles/index.less
1、增加multiplePicker 组件，点击确认数据回填到表单，点击取消，默认回到上次勾选的项。
2、弹框最大高度设置为 800px，超过则 自动增加滚动条。
=> Feature multiple picker

package.json, src/components/AddressPicker/AddressPickerGroup.tsx, src/components/AddressPicker/demo/index.tsx, src/components/AddressPicker/index.tsx
fix: AddressPicker If the required items are not filled in, they can be submitted successfully
=> fix: AddressPicker

package.json, src/components/AddressPicker/AddressPickerGroup.tsx, src/components/AddressPicker/demo/index.tsx, src/components/AddressPicker/index.md, src/components/AddressPicker/interface.ts
addressPicker modal switch with data length
=> Fix address

src/DynamicForm.tsx, src/components/AddressPicker/tests/index.test.tsx, src/components/NomarInput/tests/demos/basic.tsx, src/components/NomarInput/tests/index.test.tsx, src/components/NomarPicker/demo/index.tsx, src/components/NomarPicker/tests/demos/basic.tsx, src/components/NomarPicker/tests/demos/couplet.tsx, src/components/NomarPicker/tests/index.test.tsx, src/components/NomarSelect/demo/index.tsx, src/components/NomarSelect/tests/demos/basic.tsx, src/components/NomarSelect/tests/demos/couplet.tsx, src/components/NomarSelect/tests/index.test.tsx
修改文件的层级，以及文件的引入的路径。再修改一个bug，来自DynamicForm
=> chore: modify file level

src/components/NomarRadio/tests/demos/basic.tsx, src/components/NomarRadio/tests/index.test.tsx
=> test: add radio test

src/components/NomarCheckBox/index.tsx, src/components/NomarCheckBox/tests/demos/basic.tsx, src/components/NomarCheckBox/tests/index.test.tsx, src/components/NomarPicker/demo/index.tsx
1、增加了checkBox的测试用例
2、修改了picker测试demo修改成组件化
=> feat: add checkBox test and modify picker code

src/DynamicForm.tsx, src/components/NomarCheckBox/demo/index.tsx, src/components/NomarCheckBox/index.tsx, src/components/NomarCheckBox/tests/demos/couplet.tsx, src/components/NomarCheckBox/tests/index.test.tsx, src/components/NomarPicker/demo/index.tsx, src/components/NomarRadio/demo/index.tsx, src/components/NomarRadio/tests/demos/basic.tsx, src/components/NomarSelect/demo/index.tsx
=> feat: add checkBox test,delete unwanted code

src/components/NomarDatePicker/DatePickerGroup.tsx, src/components/NomarDatePicker/demo/index.tsx, src/components/NomarDatePicker/tasts/demos/basic.tsx, src/components/NomarDatePicker/tasts/index.test.tsx
=> 新增NomarDatePicker测试用例

src/components/CoverRadio/tests/demos/basic.tsx, src/components/CoverRadio/tests/demos/couplet.tsx, src/components/CoverRadio/tests/index.test.tsx, src/components/NomarCheckBox/tests/demos/couplet.tsx, src/components/NomarCheckBox/tests/index.test.tsx, src/components/NomarRadio/tests/demos/basic.tsx, src/components/NomarSelect/tests/demos/couplet.tsx, src/components/NomarText/demo/index.tsx
=> test: add coverRadio test, nomarTextchange to component,delete redundant code

src/components/CoverRadio/tests/index.test.tsx, src/components/NomarCheckBox/tests/demos/basic.tsx, src/components/NomarCheckBox/tests/demos/couplet.tsx, src/components/NomarCheckBox/tests/index.test.tsx, src/components/NomarPicker/tests/index.test.tsx, src/components/NomarRadio/tests/index.test.tsx, src/components/NomarSelect/tests/index.test.tsx
1、修改CoverRadio、NomarPicker、NomarRadio、NomarSelect 组件的测试代码
2、解决NomarRadio、CoverRadio的测试报错
=> test: modify CoverRadio、NomarPicker、NomarRadio、NomarSelect test code

.github/FUNDING.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/commit-convention.md, .github/workflows/ci.yml, src/components/AddressPicker/index.tsx
=> feat: add ci

src/components/CoverRadio/tests/index.test.tsx, src/components/ExtraInput/tests/demos/basic.tsx, src/components/ExtraInput/tests/index.test.tsx
=> test: add extranInput test

src/components/RangeDatePicker/tests/demos/basic.tsx, src/components/RangeDatePicker/tests/index.test.tsx
=> test: add rangeDatePicker test

src/components/NomarFile/index.tsx, src/components/NomarFile/tests/demos/basic.tsx, src/components/NomarFile/tests/index.test.tsx
=> test: add nomarFile test

src/components/CoverRadio/tests/index.test.tsx, src/components/NomarTextArea/tests/demos/basic.tsx, src/components/NomarTextArea/tests/index.test.tsx
=> test: add nomarTextArea test

src/components/DynamicForm/Dform.tsx, src/components/NomarSwitch/demo/index.tsx, src/components/NomarSwitch/index.tsx, src/utils/menu.ts
feat: 1.Main render mode changed 2.Switch layout Modification
=>  1.Main render mode changed 2.Switch layout Modification

src/components/CoverRadio/demo/index.tsx, src/components/CoverRadio/index.tsx, src/components/CoverRadio/radioGroup.tsx, src/components/NomarRadio/demo/index.tsx, src/components/NomarRadio/index.tsx, src/components/NomarRadio/radioGroup.tsx, src/components/NomarSelect/NomarSelectGroup.tsx, src/components/NomarSelect/demo/index.tsx, src/components/NomarSelect/index.tsx, src/components/NomarSelect/interface.ts, src/components/NomarText/demo/index.tsx, src/components/NomarText/index.tsx
=> chore: add defauletValue

src/components/NomarSwitch/tests/demos/basic.tsx, src/components/NomarSwitch/tests/index.test.tsx
=> test: add switch test

src/components/NomarImagePicker/demo/index.tsx, src/components/NomarImagePicker/index.tsx, src/components/NomarImagePicker/tests/demos/basic.tsx, src/components/NomarImagePicker/tests/index.test.tsx
=> test: add ImagePicker test

package.json, src/components/AddressPicker/index.tsx, src/components/AddressPicker/interface.ts, src/components/CoverRadio/index.tsx, src/components/DynamicForm/Dform.tsx, src/components/ExtraInput/index.tsx, src/components/InputItem/index.tsx, src/components/InputItem/interface.ts, src/components/MultiplePicker/index.tsx, src/components/MultiplePicker/interface.ts, src/components/NomarCheckBox/index.tsx, src/components/NomarCustom/index.tsx, src/components/NomarDatePicker/index.tsx, src/components/NomarDatePicker/interface.ts, src/components/NomarFile/index.tsx, src/components/NomarFile/interface.ts, src/components/NomarImagePicker/index.tsx, src/components/NomarImagePicker/interface.ts, src/components/NomarInput/index.tsx, src/components/NomarPicker/index.tsx, src/components/NomarPicker/interface.ts, src/components/NomarRadio/index.tsx, src/components/NomarSelect/index.tsx, src/components/NomarSelect/interface.ts, src/components/NomarSwitch/index.tsx, src/components/NomarText/index.tsx, src/components/NomarTextArea/index.tsx, src/components/RangeDatePicker/index.tsx
=> Chore title change

package.json, src/components/CoverRadio/tests/demos/basic.tsx, src/components/ExtraInput/tests/demos/basic.tsx, src/components/NomarFile/tests/demos/basic.tsx, src/components/NomarFile/tests/index.test.tsx, src/components/NomarImagePicker/tests/demos/basic.tsx, src/components/NomarPicker/tests/demos/couplet.tsx, src/components/NomarRadio/tests/demos/basic.tsx, src/components/NomarSelect/tests/demos/couplet.tsx, src/components/RangeDatePicker/tests/demos/basic.tsx, src/tests/groupUsage/groupUsageTest.tsx, src/tests/groupUsage/jsonGroupTest.tsx
=> Fix test ci

src/components/DynamicForm/Dform.tsx
=> fix: ci test

src/components/NomarCheckBox/index.tsx
=> fix: 解决NomarCheckBox单独使用时，设置默认值不生效

src/components/NomarInput/index.tsx
=> fix: input placeholder set default

package.json, src/baseComponents/InputItem/index.tsx, src/components/NomarPicker/NomarPickerGroup.tsx, src/components/NomarPicker/demo/index.tsx, src/components/NomarPicker/index.tsx, src/components/NomarPicker/interface.ts, src/components/NomarPicker/tests/demos/pc.tsx, src/components/NomarPicker/tests/index.test.tsx, src/index.less, yarn.lock
：TODO
The antd select component cannot be used normally in dumi
Already mentioned issues to dumi . https://github.com/umijs/dumi/issues/1023
=> Feat pc picker

src/components/AddressPicker/AddressPickerGroup.tsx, src/components/AddressPicker/demo/index.tsx, src/components/AddressPicker/index.less, src/components/AddressPicker/tests/index.test.tsx
Add addressPicker Refer to the component effect of Cascader
=> V4.x address picker

src/components/AddressPicker/AddressPickerGroup.tsx, src/components/AddressPicker/demo/index.tsx, src/components/AddressPicker/tests/index.test.tsx
- any feature?
- Optimize request times with AddressPicker
- no
=> feat: Optimize request times with AddressPicker

src/baseComponents/InputItem/index.tsx, src/baseComponents/PcLayout/index.tsx, src/components/NomarPicker/NomarPickerGroup.tsx, src/components/NomarTextArea/TextareaItem.tsx, src/components/NomarTextArea/index.less, src/components/NomarTextArea/index.tsx, src/components/NomarTextArea/interface.ts, src/components/NomarTextArea/tests/demos/pc.tsx, src/components/NomarTextArea/tests/demos/single.tsx, src/components/NomarTextArea/tests/index.test.tsx, yarn.lock
=> feat: area compatible PC effect

src/components/NomarRadio/demo/index.tsx, src/components/NomarRadio/index.less, src/components/NomarRadio/index.tsx, src/components/NomarRadio/radioGroup.tsx, src/components/NomarRadio/tests/demos/basic.tsx, src/components/NomarRadio/tests/index.test.tsx
=> V4.x radio

src/baseComponents/InputItem/index.tsx, src/components/NomarFile/demo/index.tsx, src/components/NomarFile/fileGroup.tsx, src/components/NomarFile/index.less, src/components/NomarFile/index.tsx, src/components/NomarFile/interface.ts, src/components/NomarFile/tests/demos/basic.tsx, src/components/NomarFile/tests/index.test.tsx, src/index.less, src/styles/index.less
=> feat: file compatible PC effect

src/components/NomarRadio/index.less, src/components/NomarRadio/index.tsx, src/components/NomarRadio/radioGroup.tsx
=> fix: v4-radio pc style

src/components/NomarCustom/CustomGroup.tsx, src/components/NomarCustom/index.less, src/components/NomarCustom/index.md, src/components/NomarCustom/index.tsx, src/components/NomarCustom/interface.ts, src/components/NomarCustom/tests/demo/basic.tsx, src/components/NomarCustom/tests/index.test.tsx, src/components/NomarPicker/index.md, src/components/NomarPicker/index.tsx, src/components/NomarPicker/tests/demos/basic.tsx
=> feat: custom compatible PC effect

src/components/NomarInput/index.md
fix: set input bug
修改 input 组件多余的 API 参数描述
=> fix: set input bug

src/PropsType.ts
fix: set IDynamicFormProps code
修改 IDynamicFormProps 的入参 children 为非必填
=> fix: set IDynamicFormProps code

src/components/NomarCheckBox/demo/single.tsx, src/components/NomarCheckBox/index.md, src/components/NomarCheckBox/tests/index.test.tsx
=> perf: complete the checkbox

src/components/NomarTextArea/demo/single.tsx, src/components/NomarTextArea/index.md, src/components/NomarTextArea/tests/demos/single.tsx, src/components/NomarTextArea/tests/index.test.tsx
- add textArea singly use test case
=> test: add textArea single use test case

src/components/NomarRadio/demo/single.tsx, src/components/NomarRadio/index.md, src/components/NomarRadio/tests/demos/single.tsx, src/components/NomarRadio/tests/index.test.tsx
- add radio singly use demo and test case
=> feat: add radio singly use demo and test case

src/components/NomarCheckBox/index.md, src/components/NomarCheckBox/tests/demos/single.tsx, src/components/NomarCheckBox/tests/index.test.tsx, src/components/NomarSelect/index.md, src/components/NomarSelect/tests/demos/single.tsx, src/components/NomarSelect/tests/index.test.tsx
修改  select 和 checkBox 组件的 jest 代码
=> perf: set select and  checkBox jest

src/components/NomarFile/tests/demos/single.tsx, src/components/NomarFile/tests/index.test.tsx
=> feat: complete file

src/components/MultiplePicker/demo/index.tsx, src/components/MultiplePicker/index.less, src/components/MultiplePicker/index.md, src/components/MultiplePicker/index.tsx, src/components/MultiplePicker/interface.ts, src/components/MultiplePicker/multiplePickerGroup.tsx, src/components/MultiplePicker/tests/demos/basic.tsx, src/components/MultiplePicker/tests/demos/single.tsx, src/components/MultiplePicker/tests/index.test.tsx
- [ x ] `npm test` passes
- [ x ] tests are included
- [ x ] documentation is changed or added
- [ x ] commit message follows commit guidelines
- any feature?
=> feat: MultiplePicker add value selected linkage
